---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-introduction"
      label: "Introduction"
      solveButton: false
    - name: "02-installsystemroles"
      label: "Installsystemroles"
      solveButton: false
    - name: "03-openhttpservice"
      label: "Openhttpservice"
      solveButton: false
    - name: "04-openarbitraryport"
      label: "Openarbitraryport"
      solveButton: false
    - name: "05-portforward"
      label: "Portforward"
      solveButton: false
    - name: "06-reset"
      label: "Reset"
      solveButton: false
    - name: "07-conclusion"
      label: "Conclusion"
      solveButton: false

tabs:
  - name: "controlnode"
    url: /wetty_controlnode/ssh/root
  - name: "rhel1"
    url: /wetty_rhel1/ssh/root
